Feature/password reset
kraud/keelapp pull request #3
Opened 2024-07-17 00:11 UTC by NicolasJuanF

Branch with implementation to reset password

2024-07-18 22:48 UTC, MatiBlanco commented on backend/controllers/userController.js
> +        console.log(error)
Es necesario el log? Tipo es la manera en la que verificaremos los erroreS?

2024-07-19 00:02 UTC, MatiBlanco approved these changes
Funciona y creo que esta bien. Deje un comentario para charlarlo, pero ta josh

2024-07-19 01:33 UTC, kraud requested changes
Funciona bien, pero arreglaría estos items antes de mergear 👍🏻

2024-07-19 01:33 UTC, kraud commented on frontend/src/pages/ResetPassword.tsx
Desde esta vista no hay forma de volver al formulario de login en caso de no querer enviar el email de reseteo de contraseña (ver text-links debajo de login/register).

2024-07-19 01:33 UTC, kraud commented on backend/controllers/userController.js
> +    try {
Si pruebo con un email que no existe, el catch se activa directamente e ignora el res.status(400) dentro de la función. Tira el erro, pero el HTTP response status es 500. Tal vez es mejor probar el trigger de errores como está en login (sin try-catch)?

2024-07-19 01:33 UTC, kraud commented on frontend/src/pages/ResetPassword.tsx
> +                        <Grid
La barra de carga no aparece mientras se espera la respuesta del servidor (hace falta un Grid padre más, que sea container, y definirle un ancho en xs al Grid que envuelve a LinerInderterminate).

2024-07-19 01:33 UTC, kraud commented on frontend/src/pages/Login.tsx
> +                                <Grid
Por alguna razón, todo el container se ensancha cuando se agrega este otro boton? La solución es poner el Grid container padre de los botones en direction={'column'}, centrar con alignItems={'center'} y agregar paddingX para el Grid que envuelve a todo. Después pedime y te paso las lineas exactas a cambiar para que quede igual que antes.

2024-07-19 01:33 UTC, kraud commented on backend/controllers/userController.js
> +    try {
Idem try-catch errores que en requestPasswordReset.

2024-07-19 01:33 UTC, kraud commented on frontend/src/pages/ResetPassword.tsx
> +                                xs={4}
Se puede agrandar un poco el boton, para que el label no quedé tan pegado a los bordes. Probé con xs={8} y se ve mejor creo.

2024-07-23 21:02 UTC, NicolasJuanF commented on frontend/src/pages/ResetPassword.tsx
> +                                xs={4}
Subí a 5. 8 no quedaba bien, quedaba muy distinto al botón submit de Login

2024-07-23 22:25 UTC, kraud approved these changes
LGTM 👍🏻

2024-07-24 22:28 UTC, MatiBlanco approved these changes

2024-07-24 22:29 UTC, merged